---
abstract: 'An OO interface to Apple Configuration Profiles.'
author:
  - 'A. Karl Kornel <karl@kornel.us>'
build_requires:
  DateTime::Infinite: '0'
  Module::Signature: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.4210'
dynamic_config: 0
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Apple-Profile
provides:
  Config::Apple::Profile:
    file: lib/Config/Apple/Profile.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Certificate:
    file: lib/Config/Apple/Profile/Payload/Certificate.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Certificate::PEM:
    file: lib/Config/Apple/Profile/Payload/Certificate/PEM.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Certificate::PKCS1:
    file: lib/Config/Apple/Profile/Payload/Certificate/PKCS1.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Certificate::PKCS12:
    file: lib/Config/Apple/Profile/Payload/Certificate/PKCS12.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Certificate::Root:
    file: lib/Config/Apple/Profile/Payload/Certificate/Root.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Common:
    file: lib/Config/Apple/Profile/Payload/Common.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Email:
    file: lib/Config/Apple/Profile/Payload/Email.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Font:
    file: lib/Config/Apple/Profile/Payload/Font.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Tie::Array:
    file: lib/Config/Apple/Profile/Payload/Tie/Array.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Tie::Dict:
    file: lib/Config/Apple/Profile/Payload/Tie/Dict.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Tie::Root:
    file: lib/Config/Apple/Profile/Payload/Tie/Root.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Types:
    file: lib/Config/Apple/Profile/Payload/Types.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Types::Serialize:
    file: lib/Config/Apple/Profile/Payload/Types/Serialize.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::Types::Validation:
    file: lib/Config/Apple/Profile/Payload/Types/Validation.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::WiFi:
    file: lib/Config/Apple/Profile/Payload/WiFi.pm
    version: v0.87.1
  Config::Apple::Profile::Payload::WiFi::EAPClientConfiguration:
    file: lib/Config/Apple/Profile/Payload/WiFi/EAPClientConfiguration.pm
    version: v0.87.1
  Config::Apple::Profile::Targets:
    file: lib/Config/Apple/Profile/Targets.pm
    version: v0.87.1
requires:
  Data::GUID: '0'
  DateTime: '0'
  DateTime::Format::Flexible: '0'
  Email::Valid: '0'
  Exporter::Easy: '0'
  File::Temp: '0'
  IO::Dir: '0'
  IO::File: '0'
  Mac::PropertyList: '1.4'
  Readonly: '0'
  Regexp::Common: '0'
  Scalar::Util: '0'
  Try::Tiny: '0'
resources:
  bugtracker: https://github.com/akkornel/Config-Apple-Profile/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/akkornel/Config-Apple-Profile
version: v0.87.1
